### ISSUE TITLE
Euler Sod Shock Tube Problem

### ISSUE THREAD

**Issue by rruizdeaustri** [brandstetter-johannes/MP-Neural-PDE-Solvers#1]
Dear Johannes,

 Thanks for making this public !!

 I would like to apply your method to the the astrophysics field 
 in a context where one has to solve hyperbolic PDEs with shocks 
 similar, for instance, to the 1D Euler equations (coupled system 
 of equations).

 My question is whether is possible to use your method 
 in such a type of PDEs. 

Thanks,

Roberto

**Comment by brandstetter-johannes** [comment]
Dear Roberto,
thank you very much for you interest!
Can you provide more information about your PDE (dimensionality, regular/non-regular grid, boundary conditions, ...)?

Thanks,
Johannes

**Comment by rruizdeaustri** [comment]
Dear Johannes,

 It's a hyperbolic PDE system with three coupled equations in the x (ie. 1 spatial component) and t domain. 
 

 The equation is the following: 
Forward Problem for 1-D Euler Equations for Compressible Flow: The Sod Problem

In this code we solve for rho, u, p  from the following equations:
                               U_t + AU_x = 0,         (x,t) in (0,1)x(0,0.2]
                              (rho,u,p)_t=0 = (1.0,0.0,1.0) 0 <= x < 0.5
                              (rho,u,p)_t=0 = (0.125,0.0,0.1) 0.5 <= x <=1
with Dirichlet boundary conditions which take the values of the initial condition at the boundaries
                               = [ rho ]       and       A =  [    u, rho, 0    ]
                                   [  u  ]                      [   0,  u, 1/rho  ]
                                   [  p  ]                      [   0, gamma*p, u ]
rho -- Density of the fluid
u   -- Velocity of the fluid - x direction
p   -- Pressure of the fluid
E   --  Total energy of fluid
We relate the pressure and energy by the equation of state of the form
                                             p = (gamma - 1) ( rho*E - 0.5*rho||u||^2)
For this problem we use gamma = 1.4

 Thanks !!
 Rbt

**Comment by rruizdeaustri** [comment]
BTW I attach a solution using numerical methods (pyclaw) and a standard PINN method for t = 0.2 sec. The idea is to see if your method can do better than the PINN in the discontinuities. 

[euler1D_t02.pdf](https://github.com/brandstetter-johannes/MP-Neural-PDE-Solvers/files/8603363/euler1D_t02.pdf)
 
Thanks,
Rbt

**Comment by brandstetter-johannes** [comment]
Dear Roberto,
thank you very much for the detailed information. Yes, this in fact exactly looks like the kind of problem we where trying to tackle. 
I assume you will have a non-regular grid?
Instead of having an output (input) of n_timesteps*n_x you will now have n_timesteps*n_x*4 -> rho, u, p, E. T
Johannes

**Comment by rruizdeaustri** [comment]
Hi Johannes,
The spatial grid can be regular between 0 and 1 (ie. taking a fixed number of steps). I guess you mean that, right ?
I will have a look at your code and try to implement it. If would be good if your approach works in this context since in these problems (ie. standard in astrophysics) pinns fail.
Will you be able to give me a hand in the implementation if I have some issue ? 
Thanks a lot !!
Rbt

**Comment by brandstetter-johannes** [comment]
Yes this is what I meant!
Please don't hesitate to contact me, I am happy to assist for the implementation.
I guess we can close this issue and follow-up via email :)

**Comment by rruizdeaustri** [comment]
Yes sure. 

 Thanks a lot !!
