### ISSUE TITLE
Incompatibility of F.conv1d with 4D tensors in __getItem__ of HDF5Dataset in utils.py

### ISSUE THREAD

**Issue by pkhudov** [brandstetter-johannes/MP-Neural-PDE-Solvers#10]
Hello,

Thank you for an amazing paper and great code!

I came across an error that occurs when processing the dataset, which has dimensions `[batch_size, channels, spatial_res, temp_res]`, using `F.conv1d`, in these parts of `utils.py`:
https://github.com/brandstetter-johannes/MP-Neural-PDE-Solvers/blob/76f07bb26a1829ac5ba6665956f51f645ad6e322/common/utils.py#L86-L87
https://github.com/brandstetter-johannes/MP-Neural-PDE-Solvers/blob/76f07bb26a1829ac5ba6665956f51f645ad6e322/common/utils.py#L104
https://github.com/brandstetter-johannes/MP-Neural-PDE-Solvers/blob/76f07bb26a1829ac5ba6665956f51f645ad6e322/common/utils.py#L108
It expects either 2D unbatched or 3D batched, while our data is 4D. The convolution weights of shape `[1, 1, 1, 5]` suggest a 1D-like convolution in a 2D context, which `F.conv1d` cannot do. 

I suggest replacing it with `F.conv2d`, which fixes the issue while keeping the intended 1d convolution operation due to weights' shape.

**Comment by brandstetter-johannes** [comment]
Dear @pkhudov you are right. Please proceed an make a PR! Thanks a lot
