### ISSUE TITLE
Error on the WE3 generation?

### ISSUE THREAD

**Issue by LouisSerrano** [brandstetter-johannes/MP-Neural-PDE-Solvers#13]
Hi,

I was going over the generation script of WE3 in `generate/generate_data.py` and I noticed that the bc_right was not modified in this mixed setting with Neumann or Dirichlet conditions. I guess the line 197 is at fault: `bc_left = np.random.randint(0, 2, size=1)` should be `bc_right = np.random.randint(0, 2, size=1)`, but maybe this is intended. Should we always keep the right boundary condition as dirichlet for this case ?
Best,
Louis

**Comment by brandstetter-johannes** [comment]
You are right, can you do a PR?

**Comment by LouisSerrano** [comment]
Sure, no problem.
