### ISSUE TITLE
Experiments and results on Fourier Neural Operator

### ISSUE THREAD

**Issue by YichengDWu** [brandstetter-johannes/MP-Neural-PDE-Solvers#2]
Hello,

Thank you for the excellent paper.

I am very interested in the experimental results of applying some of the techniques to the FNO. However, I faild to find the corresponding code in this repository.Maybe I missed it or is the code not yet released?

**Comment by brandstetter-johannes** [comment]
Hi @MilkshakeForReal ,
directly in this repo there is not FNO implementation yet. 
However, we extensively used FNO for regular grids in this repo: https://github.com/brandstetter-johannes/LPSDA
This is basically our training framework with FNO on regular grids. You can try out different things there. Hope this helps

**Comment by YichengDWu** [comment]
Thank you for your reply!
