### ISSUE TITLE
A typo in Appendix F

### ISSUE THREAD

**Issue by YichengDWu** [brandstetter-johannes/MP-Neural-PDE-Solvers#3]
![2D_%3FM3)83DMNWXN$44O2](https://user-images.githubusercontent.com/38997672/170813808-2140c3ac-2012-4cde-b532-1cfed1872a46.png)

I believe the third-to-last line here should read
`target <-data(t+NK:t+(N+1)K)`

It's easy to see this if we let `N=1`

**Comment by brandstetter-johannes** [comment]
thanks a lot for spotting this @MilkshakeForReal! you are absolutely right!
