### ISSUE TITLE
Code for FNO-PF model

### ISSUE THREAD

**Issue by Winfriedvdd** [brandstetter-johannes/MP-Neural-PDE-Solvers#4]
Hi, I am having some issues reproducing the FNO-PF results. I am working on experiment E1, using the burgers equation and the 1d FNO model from their github rep. With only the Push-forward applied I arrive at reasonable results, but I can't quite figure out how the temporal bundling is implemented. 
One could for instance just change the output size of the last layer to match the time window, whereas another option is to apply the approach as in equation 10 in your paper, possibly with the extra convolutional decoder layers included.
Which approach did you use in the experiments?

Thanks in advance,
Winfried

**Comment by brandstetter-johannes** [comment]
Hi @Winfriedvdd thank you very much for your interest.
Including temporal bundling into FNO is a bit tricky, there are many possibilities to do that.
Maybe you have a look at our other repo, and especially here: https://github.com/brandstetter-johannes/LPSDA/blob/master/experiments/models_fno.py#L66

There we used FNO with temporal bundling, pushforward (and Lie point symmetry data augmentation) on a regular grid with periodic boundaries, i.e. where FNOs really shine. This is basically also how we did it for the Message Passing paper! Temporal bundling with FNO like approaches is very powerful (at least for low dimensional data)

Hope this helps,
Johannes

**Comment by Winfriedvdd** [comment]
Thanks for the reply! This is also a very nice paper indeed.
I see that in your implementation of the FNO network you also include dt as
a channel dimension in the input (rather than just the spatial locations as
in the original FNO implementation). Is this required to make the temporal
bundling work?

Kind regards,

Winfried

Op wo 7 sep. 2022 om 14:27 schreef brandstetter-johannes <
***@***.***>:

**Comment by Winfriedvdd** [comment]
And could you perhaps send the code for the FNO model that is used
specifically in the message passing GNN paper? Just in case I still can't
get it to work :)

Kind regards,

Winfried

Op ma 19 sep. 2022 om 15:43 schreef Winfried van den Dool <
***@***.***>:

**Comment by brandstetter-johannes** [comment]
Hi Winfried
Adding dt and dx is not required, we did it to be more consistent with origin FNO implementation. This code I pointed you to is the implementation we used. FNO is just having a harder time because they have to model a shock and they have to generalize across parameters. So if you want to see 1D problems where FNO shines I would recommend the LPSDA datasets :)

**Comment by Winfriedvdd** [comment]
Hi and thanks again! One more question, the FNO code in the LPSDA dataset
uses 32 modes and a width of 256, as well as 5 layers (instead of 16, 64, 4
used in original FNO implementation I believe). This would give it approx
10 million parameters. Is this the one you use in the experiments or are
you using different hyperparameters? (In the paper you mention approx 1
million parameters, but I wasnt sure whether this solely refers to the
MP-Neural-PDE-Solver or also to the other models.

Winfried

Op wo 21 sep. 2022 om 15:09 schreef brandstetter-johannes <
***@***.***>:

**Comment by brandstetter-johannes** [comment]
Your are right of course, we adjust to 1million parameters, 4 layers, 12 modes and 32 hidden channels. What if we take this discussion offline? Just shoot me an email.

Johannes
