### ISSUE TITLE
Code for 2D MP-Neural-PDE-Solver

### ISSUE THREAD

**Issue by Winfriedvdd** [brandstetter-johannes/MP-Neural-PDE-Solvers#5]
Hi, another code request ;)
Is there by any chance code available for the 2d variant of the Message-Passing neural network used?
Or any information regarding architecture/hyperparameter choices used?
It would help me a lot!

Kind regards,

Winfried

**Comment by brandstetter-johannes** [comment]
I can give you some snippets, just shoot me an email :)

**Comment by brandstetter-johannes** [comment]
closed after private conversation, who wants code snippets please contact me!

**Comment by liluo2** [comment]
Here! @brandstetter-johannes
