### ISSUE TITLE
Question related to test process..

### ISSUE THREAD

**Issue by dkssudgktpdydn** [brandstetter-johannes/MP-Neural-PDE-Solvers#9]
Hello, I have read your paper. It is excellent research.
I have one question.

When examining the calculation of the unroll loss during the testing process, 
it appears that the starting time step is 50 (in the case of the E1 dataset).

Does the starting value use the ground truth obtained from the PDE? 
In other tests mentioned in the paper, is the ground truth value included in addition to the initial condition for the initial timestep?

I appreciate you taking the time to read. 
Thank you very much, and have a great day!

**Comment by brandstetter-johannes** [comment]
The starting time step uses ground truth data, but ground truth data are excluded from loss calculations. Does this answer the question?
